language: node_js
addons:
  sonarcloud:
    organization: polexrufous
    token:
      secure: Kxi20qdanm2nZtg75j3BwTOyRNhRZAXs04QcYmdvA6mYY++OEe76wJiuqGmcU2fWf+XzUXoAEUPiTHZtpVqufOMtCmx6aduzA70++kwzo1kIC9r9Bh19n4L7J0eklEM6qMzhQMaCk5yV1xjsl+LyJCOcaq/uXf7nmFU1k1vujatsATOZhkiQKMe9FTuTli4OAqfSNal8sx+ruU5BMQss9eMcyPlxfajH9E616zdSza4veyLULJy4lmo8/rb4oD/kqqX8i9i9rcTv9FqEFugzRPUrWAnFR9LMtaaT8zk2xlFJQp4AQ2Fgd2epEk7r/xkPIXyJlJzQFbqmk+T5ytiNESpleVVMQMngj+/OfuU9jjertQImDaiJvzsJ1Dau26XbZMDvQvVPhAbXkVFa3iU31OrcHvGPYajn4GiaykfbaQXrn/YHXjEpFJEI/xNQzrUsxb1Xm9z0ZbNzq0PlGji0yFk5eLWrh55dPSZKlrHIFLuxFjqfC7RjQ02bJ+kSbsKvnOyl7/EyTZH7MO1oTWSbcY22lgVccJOgUafvicPEcPmPhDJuO1zi7Gc+ZZ1G7o4uBK2xiUhresVu9LHm8abz1UeG3VGjN+KjiJQTn4Ol9CFRXxU8xAfDniQHpz5yQC909ClTHkveicsWcla69gty2ylBnscC9MHFtMkCwa3qMLk=

deploy:
  provider: heroku
  api_key:
    secure: Y9XSy43ZbdibyYVHDHJWctNjW2zjQokRpELdvnX6WkNwgHEeDJSdudBW+EZwq9Sbx5M4lem0sg0P5W3cvg83htFbSmZ/q54OaQyNzp4n2dlo3Ee2FtkmCh0FbyYXBBM1kvqZko+d5I/wiwnkvZp+e7Lb+3gJO1lh01di5GIC4aFbXSL7j/YEEKp/sbWRVr84/XRMpYXr2oG22+AlzrRu/3zuSszI8XhPs0CMDMfqFxWPhVvB3fSms9Cn9CrZCmWftWNzEmmwHndpqHQJCP9KDv059l17v9PXV5Mb5OuWBCn58WPdv4CN/MitZmSaBBk02GxVrxiAC9ENhUKlYsIMYoTOyJ4sAu3RCCeWqE0iZSw5CX0rschSY6fVk9Y6SY+VIlhgfwzDFCMZvNBHt/ROFyXDYETabSEH9UN2v/OpMutKkclI6e0lJS2I6yPkQXEr257jhgVUfA3pqvjmiby0I+bdSunEzsHMgbJqN/ByfDL42jkTL21TqTwRX/B5c1vg97uVhQ5ASoeBxoFOIkvLey+VhQiMLSmSTXc8oa5QQR4EAQAofMfSNaRM/Jngtyx+l72h0BvxOUJLuhIYIesMhsDmHv+D+Md7e8tRnkbeJSphqjBy9tQQixQNfNk4nm+op7nQzwo6dQIFOKTvYLrYRjipcL7zapN89uWgtDxUNzA=
  app: ng-reactive

