language: node_js
deploy:
  provider: heroku
  api_key:
    secure: Y9XSy43ZbdibyYVHDHJWctNjW2zjQokRpELdvnX6WkNwgHEeDJSdudBW+EZwq9Sbx5M4lem0sg0P5W3cvg83htFbSmZ/q54OaQyNzp4n2dlo3Ee2FtkmCh0FbyYXBBM1kvqZko+d5I/wiwnkvZp+e7Lb+3gJO1lh01di5GIC4aFbXSL7j/YEEKp/sbWRVr84/XRMpYXr2oG22+AlzrRu/3zuSszI8XhPs0CMDMfqFxWPhVvB3fSms9Cn9CrZCmWftWNzEmmwHndpqHQJCP9KDv059l17v9PXV5Mb5OuWBCn58WPdv4CN/MitZmSaBBk02GxVrxiAC9ENhUKlYsIMYoTOyJ4sAu3RCCeWqE0iZSw5CX0rschSY6fVk9Y6SY+VIlhgfwzDFCMZvNBHt/ROFyXDYETabSEH9UN2v/OpMutKkclI6e0lJS2I6yPkQXEr257jhgVUfA3pqvjmiby0I+bdSunEzsHMgbJqN/ByfDL42jkTL21TqTwRX/B5c1vg97uVhQ5ASoeBxoFOIkvLey+VhQiMLSmSTXc8oa5QQR4EAQAofMfSNaRM/Jngtyx+l72h0BvxOUJLuhIYIesMhsDmHv+D+Md7e8tRnkbeJSphqjBy9tQQixQNfNk4nm+op7nQzwo6dQIFOKTvYLrYRjipcL7zapN89uWgtDxUNzA=
  app: ng-reactive

